### PR TITLE
add callback style, callback timing issue fix, update readme

### PR DESCRIPTION
**Pull request by devmario**
Thx to your nice animation code.

I want you to take my PR
## details
- update callback called before begin callback.(update callback need call when after begin callback)
- begin callback called only once.(begin callback need call when restart) 
```js
anim.begin = undefined;
```
- callback need promise style #4 (need callback setup function with all function return anime)
- update readme about this PR

## example
```js
var _anim = anime({
  ...
  loop: false,
  autoplay: false
});

_anim
.begin((function(anim) {
    console.log("begin", this._anim);
}).bind(this))
.play()
.update(function(anim) {
})
.complete(function(anim) {
    console.log("complete", anim);
    anim.play();
});
```

## check my fiddle
https://jsfiddle.net/devmario/9d8orpg5/3/

thx u for reading
;)

### CODE REVIEW

**Comment by SaulDoesCode** [comment]
I just implemented these changes on my fork, thank I think making things chainable like promises is cool. thanks for suggesting it

**Comment by juliangarnier** [comment]
What is the real advantage of having:

```javascript
var myCompleteFunc = function(anim) {...};
var myAnimation = anime({
  targets: 'div',
  translateX: '13rem'
});

myAnimation.completed(myCompleteFunc);

```

instead of:

```javascript
var myCompleteFunc = function(anim) {...};
var myAnimation = anime({
  targets: 'div',
  translateX: '13rem',
  complete: myCompleteFunc
});
```

?

**Comment by devmario** [comment]
- More easy change handler at animation run-time
- More readable

My case need change update callback at animation runtime often.

This chainable is optional.
Still can specify a callback when create the instance.

For example
```js

var beginfunc = function(anim) {
  console.log("begin", this._anim);
}
var updatefunc1 = function(anim) {
    if($(".red").offset().left > 100) {
       amin.pause();
       anim.settings.update = null;//no more check offset left
    }
}
var completefunc1 = function(anim) {
    console.log("complete 1", anim);
    anim.settings.complete = completefunc2;
    anim.play();
}
var completefunc2 = function(anim) {
     console.log("complete 2", anim);
}
var anim = anime({
  ...
  loop: false,
  autoplay: false,
  begin: beginfunc.bind(this),
  update: updatefunc1,
  complete: completefunc1
});
anim.play()
```
Instead of:
```js
var anim = anime({
  ...
  loop: false,
  autoplay: false
}).begin((function(anim) {
    console.log("begin", this._anim);
}).bind(this)).play().update(function(anim) {
    if($(".red").offset().left > 100) {
       amin.pause().update(null);//no more check offset left
    }
}).complete(function(anim) {
    console.log("complete 1", anim);
    anim.complete(function(anim) {
        console.log("complete 2", anim);
    }).play();
});
```
This code is running animated twice. And if ".red" dom offset is more than 100, animation is paused only once.

Do not like this style of code? ;(

**Comment by juliangarnier** [comment]
No, actually I think it's probably better this way 👍 
But it should be one or the other, I don't want overlaps in the API.

So if we remove the current `begin`, `update`, and `complete` parameters from the API, it would be better to ship this in a v1.1.

I created a v1.1 branch to keep the master clean.

Feel free to do you PR here https://github.com/juliangarnier/anime/tree/v1.1.

Also, I think this should be implemented in parallel of #4.

**Comment by devmario** [comment]
Yes @juliangarnier 
I will send PR to you ASAP

**Pull request closed without merging**
