### PR TITLE
Deprecated path.el.getPointAtLength

### PR DESCRIPTION
**Pull request by jeroenrinzema**
Resolves path.el.getPointAtLength is not a function error in #275

### CODE REVIEW

**Comment by jeroenrinzema** [comment]
I removed the if statement that caused the problem. @naivefun could you please confirm that this version of anime resolved the Firefox issues?

**Comment by jeroenrinzema** [comment]
Resolves issue: #275

**Comment by jeroenrinzema** [comment]
@eybarta could you please create a jsfiddle? I created a [example](https://jsfiddle.net/1ugdz6vt/) with this pull request included.

**Comment by eybarta** [comment]
sorry for the delay.. here's a jsfiddle, you can see the error in the console..
thx!
https://jsfiddle.net/eybarta/ezm0kdgL/2/

**Pull request closed without merging**
