### PR TITLE
Change package.json main to non-minified script #249

### PR DESCRIPTION
**Pull request by alexchantastic**

### CODE REVIEW

**Comment by alien35** [comment]
It won't run on ES5 though.

**Comment by alexchantastic** [comment]
@alien35 you're absolutely right. I did not have that in mind!

What is the best practice for instances like these where you want to maintain ES5 compatibility, but the source file would need to be transpiled?

Is having a `src` and `dist` folder an option? The `src` folder holds the non-transpiled file and `dist` holds the transpiled pretty printed and minified files. `main` in `package.json` and `bower.json` would then point to `dist/anime.js`.

**Comment by renchap** [comment]
Usually you have a transpiled but non-minified version in `dist`:
- `dist/anime.js`: transpiled to ES5 but not minified
- `dist/anime.min.js`: transpiled and minified

I dont really know how to do it properly with `google-closure-compiler-js`, as it seems to do both at the same time.

**Comment by alexchantastic** [comment]
Closing this in favor of #313.

**Comment by juliangarnier** [comment]
Merged in [v3.0.0 branch](https://github.com/juliangarnier/anime/tree/3.0.0).

**Pull request closed without merging**
