### PR TITLE
event system implemented

### PR DESCRIPTION
**Pull request by SaulDoesCode**
I implemented everything as discussed feel free to offer constructive criticism
and/or voice your concerns over certain changes you might not agree with.
merci

### CODE REVIEW

**Comment by SaulDoesCode** [comment]
These all do the same thing
```javascript
        // event system style
        anim.on('complete', function(anim) {
          console.log('1 done');
        });
        // normal method style
        anim.complete(function(anim) {
          console.log('2 done');
        });
       // promise style
        anim.complete().then(function(anim) {
          console.log('3 done');
        });
```

**Comment by SaulDoesCode** [comment]
final minified size with uglify.js is 16.3kb, I suggest you use google-closure compiler final size with google closure is 10.6kb

**Comment by SaulDoesCode** [comment]
The event system is actually adapted from my [craft-observables](https://www.npmjs.com/package/craft-observable) project

**Comment by juliangarnier** [comment]
There are still 4 ways of doing the same thing...
Sorry but this was supposed to be an example of the event system, why did you added the old methods?
And you also implemented `anim.complete().then`, i thought you didn't like the idea.

Again, I don't want too much overlaps in the API.

The goal here is to provide a way to have chainable methods and support promises.
I thought you wanted to unify all of that using an event system, with promises support using `once`...

And by looking at the event system code, I think that add too much complexity, for little benefits.
I can't find any good use cases where I'll need to use `off` and things like that.

**Comment by juliangarnier** [comment]
What do you think of a simple system like that:
```
    myAnimation.on('complete', function(anim) {
      console.log('completed');
      anim.play(); // will re-play the animation indefinitely
    });

    myAnimation.once('complete').then(function(anim) {
      console.log('completed once');
      anim.play(); // will re-play the animation only once
    });
```

**Comment by SaulDoesCode** [comment]
The event system exists internally so as long as it is implemented it will be possible to 
call things using the event system style.
it is one method and it is purely optional if you wish to omit it from the documentation for fears of complexity then that is fine.
```javascript
       // event system style
        anim.on('complete', function(anim) {
          console.log('1 done');
        });
```
I very much like this syntax you proposed it encompases both the event system's style and the promise style.
```javascript
     myAnimation.on('complete', function(anim) {
      console.log('completed');
      anim.play(); // will re-play the animation indefinitely
    });
    myAnimation.once('complete').then(function(anim) {
      console.log('completed once');
      anim.play(); // will re-play the animation only once
    });
```
You are correct in that I do not favor this ``anim.complete().then`` way of doing it, I like your way.
I agree Overlaps in the API might be a little bit confusing and clunky. 
I'm going to attempt to implement your syntax but bear in mind that the ``anim.on(type , func)`` will still be possible due to the eventsys so perhaps you might chose to omit it from the standard examples and docs.

**Comment by juliangarnier** [comment]
the above code can be achieve with only 2 new functions

```
    anim.on = function(e, cb) {
      anim.settings[e] = cb;
      return anim;
    }

    anim.once = function(e) {
      return new Promise(function(cb) {
        anim.on(e, cb);
      });
    }
```

**Comment by SaulDoesCode** [comment]
You can't have more than one 
```javascript
       myAnimation.on('complete', function(anim) {
         console.log('completed');
         anim.play(); // will re-play the animation indefinitely
       });
      // breaks the first one
       myAnimation.on('complete', function(anim) {
            console.log('completed');
            anim.play(); // will re-play the animation indefinitely
       });
```

**Comment by SaulDoesCode** [comment]
I'm refactoring the event system I am making it smaller and supporting only promise style. 
will update when it is ready

**Comment by juliangarnier** [comment]
I know, but do we really need more on complete call?

Give me one real world example where this cannot be done by passing multiple functions in one complete callback.

**Comment by SaulDoesCode** [comment]
You are building a side bar or some other form of animated navigation on a website.
certain parts of the website needs to change when the animation is called. the changes happen at different stages from within nested asynchronous code like fetch requests and such.
new elements get created and need to be bound to the animation to listen for state changes.

and besides that it would be really nice if it were possible you might not see a use case but I think other's might, anime is a very nice compact animation library that is way smaller than many competitors
adding this feature will allow it to be used in new different ways. Reacting to changes in animations from multiple listeners in different parts of the code gives a user freedom and makes anime more flexible.

also internally using the emit function allows several listeners to react to events, this would also allow new events to be emited from different parts of the library in future without the need to add extra abstraction it makes it more future proof.

please hear me out. I am refactoring the whole event system now when it is ready I'll update and you can see for your self. but if you don't like it I will understand and respect that decision.
thanks for your time

**Comment by SaulDoesCode** [comment]
Have a look now and tell me if it's worth anything

**Comment by juliangarnier** [comment]
I understand your point, but anime was designed to animate things.
Having a callback when the animation is complete is useful in the context of animation, that's why I added it.
Controlling the ways things react in an application is an other problem, and I don't think it should be solved by an animation library.
I'll focus on simple promises implementation for now, that should be enough for the methods/callbacks part.
Hope you understand.

**Comment by SaulDoesCode** [comment]
I understand, however I will maintain the fork though.
even though you don't agree on the need to have the event system is the code any good? 
lot of hours went in there.
Perhaps you'd let me maintain this branch on the main repo as a spin off that keeps in sync with the main repo? Won't have to do anything I'll keep it up to date and the main one can remain just as you like it.

**Comment by juliangarnier** [comment]
The events part looks good. 
Not sure about some of the new compression optimisation (I might reuse a few though).
I don't see the need of keeping this branch on the main repo, feel free to fork and update the branch on your side, but I prefer keeping this repo clean as possible.

**Pull request closed without merging**
