### PR TITLE
[WIP] Tests Progress

### PR DESCRIPTION
**Pull request by mubaidr**
DO NOT MERGE THIS REQUEST, IT SERVES PURPOSE OF TRACKING PROGRESS, PLEASE

Preparation
-
- [x] Setup Jest and add tests scripts & coverage report
- [x] Enable continuous integration

Tests
-
  - [x] Library exports
  - [x] TARGETS
  - [x] PROPERTIES
  - [x] PROPERTY PARAMETERS
  - [x] ANIMATION PARAMETERS
  - [x] VALUES
  - [x] KEYFRAMES
  - [x] STAGGERING
  - [x] TIMELINE
  - [x] CONTROLS
  - [x] CALLBACKS & PROMISES
  - [x] SVG
  ~~EASINGS~~
  - [x] HELPERS

Coverage Report
-
https://codecov.io/gh/mubaidr/anime/branch/tests

### CODE REVIEW

**Comment by mubaidr** [comment]
@juliangarnier I am writing tests for `staggering`. Can you please help me understand behavior? 

For this configuration:
```js
const target = [{data: 0}, {data: 0}, {data: 0}, {date: 0}];

    const animation = anime({
      targets: target,
      autoplay: false,
      easing: 'linear',
      duration: 100,
      data: anime.stagger([0, 20])
      //expected (index:target value):  0: 5, 1: 10, 2: 15, 3:20
    });
```
I get this output: 
```bash
# 50 seek
      [ { data: 0 },
        { data: 3.3333333333333335 },
        { data: 6.666666666666667 },
        { date: 0 } ]

# 100 seek
      [ { data: 0 },
        { data: 6.666666666666667 },
        { data: 13.333333333333334 },
        { date: 0 } ]

# 150 seek
      [ { data: 0 },
        { data: 6.666666666666667 },
        { data: 13.333333333333334 },
        { date: 0 } ]

# 200 seek
      [ { data: 0 },
        { data: 6.666666666666667 },
        { data: 13.333333333333334 },
        { date: 0 } ]
```

**Comment by juliangarnier** [comment]
Hey, without having tried the code, this looks like a bug on the staggering value calculation in this specific case.
I guess the tests are working!
I'll have a look a this.

**Comment by mubaidr** [comment]
Ah. Nevermind, there is typo in the code 🤦‍♂️

**Comment by mubaidr** [comment]
@juliangarnier Currently this issue blocks any advancement for svg tests, since the method used is not standard and deprecated it is not available in `jsdom`, also it will be removed in future browser versions and will break svg features: https://github.com/juliangarnier/anime/issues/275

We have currently ~81% coverage. Which will be improved over the time. 

I am re-basing this pull-request to fix merge issues.

**Comment by mubaidr** [comment]
Any update?

**Comment by mubaidr** [comment]
No love for this effort? :(

**Comment by juliangarnier** [comment]
> No love for this effort? :(

Not at all, but will wait for the next major release to merge the tests.

**Comment by mubaidr** [comment]
Cool. Let me know how can these tests can be further improved.

**Pull request merged**
