### PR TITLE
Update build script & exports

### LINKED ISSUE #249: Node modules' main scripts shouldn't be minified
This package sets [`"main": "anime.min.js"`](https://github.com/juliangarnier/anime/blob/ae9eb90ab66e92f89dad8f9b59e9df3928c16991/package.json#L5). This breaks npm convention and makes debugging stack traces almost impossible. It's ok to include a minified version in the published package, but please consider changing the main script to `"main": "anime.js"`.

### PR DESCRIPTION
**Pull request by lukeed**
This refactors the build script to use Rollup & Buble, which produces pure ES5 code under different module targets.

I've also replaces `closure-compiler` with Buble because, when GCC is left unconfigured, Buble produces smaller outputs & requires far less configuration too. In reading some of the related issues, I gathered that dealing with a bunch of build config was dreaded & a big hesitation in changing the current setup. 😅 

> Although there are browser `targets` passed to Buble, it's practically pure ES5. These can also be dropped since they're not really changing the output in Anime's case.

As for build stats, the previous GCC build script was producing a `7.4kb` (gzip) file in ~5 seconds. This PR produces all 3 exports in less than 1 second, and the UMD output is `5.4kb` (gzip)! 🎉 

> I've also logged the gzip size at the end of every build.

I don't have any Anime.js apps to test the new builds with, but I'm fairly confident it'll be the same results. The only source code I changed was [this line](https://github.com/juliangarnier/anime/blob/master/anime.js#L207), which now is `.apply(null, ...)`. I think `this` was either `undefined` or the `window` global, either of which weren't used within `bezier` anyway.

Lastly, `package.json` is setup to export all 3 file types correctly. The only real change here is that the `main` export points to the CommonJS file, which it should (#249). Additionally, the `module` key is used for ESM and then the `umd:main` is for the UMD type.

---

Closes #249, #285, #134, #253

### CODE REVIEW

**Comment by juliangarnier** [comment]
Looks really solid!
I'll try to find some time to test this more carefully later in the week.

Thank you!

👍

**Comment by lukeed** [comment]
No problem! Let me know if you have any questions~!

**Comment by lukeed** [comment]
Hey Julian, did you have any questions or concerns about this? I'm happy to help out and address them if you do!

**Comment by juliangarnier** [comment]
Hey,

Yes sorry, I checked quickly and found some issues with the .min file when I tried to run some basic example from the doc.
It's currently hard to test since most of the examples are broken due to some API changes.
So I decided to stay focus on finishing v3.0 and cleaning the new documentation / examples first, and make sure everything is working properly before changing the build system.

I plan to finish the new documentation today or tomorrow, then merge everything in your branch and see how it goes from there.

A few points though, not sure about Bubble: the min file is actually bigger than my latest tests with the closure-compiler on v3.0.
And I want to avoid having to much dependencies in the repo, so I think we can remove gzip-size and pretty-bytes from the build setup.

**Comment by lukeed** [comment]
Hey, no worries! It's your project 😆 I included them as devDependencies so that they'd only be installed for those developing within the repo -- installers would not download any of these.

Once you're done, it'd be interesting to see the size comparisons between Buble and GCC. GCC would definitely be smaller if configured correctly, but (last I saw) it wasn't configured at all.

Not worth worrying about this until 3.0 is steady, otherwise we'll always be merging 😜 

Good luck finishing up!

**Comment by juliangarnier** [comment]
Hey,

Finally found the time to merge your PR!

I had to change the umd name to `pkg['umd:name']` instead of `pkg.name`.
The uglify output is still a little bit bigger than the google closure compiler one, but it's fine. We can stick with it since it's waaay faster.

Otherwise everything looks good!

Thanks a lot for the PR.

Let me know if you see something wrong!

**Comment by lukeed** [comment]
Awesome, thanks! I'll poke around in a little bit & see if there's anything else I can add.

**Pull request merged**
