### PR TITLE
Fix begin callback

### PR DESCRIPTION
**Pull request by Disorrder**
Run `begin` when animation starts in timeline instance since 2nd instance

bug example: https://codepen.io/Disorrder/pen/WjyZqw

### CODE REVIEW

**Comment by Disorrder** [comment]
Well, nobody reviewed? :(

**Comment by juliangarnier** [comment]
Sorry, I hope to find some time in August to review all the PRs / Issues and release v2.5.

**Comment by Disorrder** [comment]
Please, fix this tiny string of code. I have to clone anime from my fork in every project... No needs to merge PR, just make same commit x_x

**Comment by Disorrder** [comment]
Ah, it seems, bug already fixed at another commit. Well, thank you

**Pull request closed without merging**
